# Generated by Django 4.0.4 on 2022-04-19 14:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_semacento', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fonte', models.CharField(blank=True, max_length=255, null=True)),
                ('p_1276_1300', models.FloatField(blank=True, null=True)),
                ('p_1301_1325', models.FloatField(blank=True, null=True)),
                ('p_1326_1350', models.FloatField(blank=True, null=True)),
                ('p_1351_1375', models.FloatField(blank=True, null=True)),
                ('p_1376_1400', models.FloatField(blank=True, null=True)),
                ('p_1401_1425', models.FloatField(blank=True, null=True)),
                ('p_1426_1450', models.FloatField(blank=True, null=True)),
                ('p_1451_1475', models.FloatField(blank=True, null=True)),
                ('p_1476_1500', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tipo', models.CharField(choices=[('CONFLITO', 'conflito'), ('CLIMATICO', 'evento_climatico'), ('FOME', 'fome'), ('PESTE', 'peste')], default='CLIMATICO', max_length=10)),
            ],
            options={
                'db_table': 'eventos_climaticos',
            },
        ),
        migrations.CreateModel(
            name='Conflito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_semacento', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fonte', models.CharField(blank=True, max_length=255, null=True)),
                ('p_1276_1300', models.FloatField(blank=True, null=True)),
                ('p_1301_1325', models.FloatField(blank=True, null=True)),
                ('p_1326_1350', models.FloatField(blank=True, null=True)),
                ('p_1351_1375', models.FloatField(blank=True, null=True)),
                ('p_1376_1400', models.FloatField(blank=True, null=True)),
                ('p_1401_1425', models.FloatField(blank=True, null=True)),
                ('p_1426_1450', models.FloatField(blank=True, null=True)),
                ('p_1451_1475', models.FloatField(blank=True, null=True)),
                ('p_1476_1500', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tipo', models.CharField(choices=[('CONFLITO', 'conflito'), ('CLIMATICO', 'evento_climatico'), ('FOME', 'fome'), ('PESTE', 'peste')], default='CONFLITO', max_length=10)),
            ],
            options={
                'db_table': 'conflitos',
            },
        ),
        migrations.CreateModel(
            name='Fome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_semacento', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fonte', models.CharField(blank=True, max_length=255, null=True)),
                ('p_1276_1300', models.FloatField(blank=True, null=True)),
                ('p_1301_1325', models.FloatField(blank=True, null=True)),
                ('p_1326_1350', models.FloatField(blank=True, null=True)),
                ('p_1351_1375', models.FloatField(blank=True, null=True)),
                ('p_1376_1400', models.FloatField(blank=True, null=True)),
                ('p_1401_1425', models.FloatField(blank=True, null=True)),
                ('p_1426_1450', models.FloatField(blank=True, null=True)),
                ('p_1451_1475', models.FloatField(blank=True, null=True)),
                ('p_1476_1500', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tipo', models.CharField(choices=[('CONFLITO', 'conflito'), ('CLIMATICO', 'evento_climatico'), ('FOME', 'fome'), ('PESTE', 'peste')], default='FOME', max_length=10)),
            ],
            options={
                'db_table': 'fomes',
            },
        ),
        migrations.CreateModel(
            name='Peste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_semacento', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fonte', models.CharField(blank=True, max_length=255, null=True)),
                ('p_1276_1300', models.FloatField(blank=True, null=True)),
                ('p_1301_1325', models.FloatField(blank=True, null=True)),
                ('p_1326_1350', models.FloatField(blank=True, null=True)),
                ('p_1351_1375', models.FloatField(blank=True, null=True)),
                ('p_1376_1400', models.FloatField(blank=True, null=True)),
                ('p_1401_1425', models.FloatField(blank=True, null=True)),
                ('p_1426_1450', models.FloatField(blank=True, null=True)),
                ('p_1451_1475', models.FloatField(blank=True, null=True)),
                ('p_1476_1500', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tipo', models.CharField(choices=[('CONFLITO', 'conflito'), ('CLIMATICO', 'evento_climatico'), ('FOME', 'fome'), ('PESTE', 'peste')], default='PESTE', max_length=10)),
            ],
            options={
                'db_table': 'pestes',
            },
        ),
    ]
